dist: trusty
language: node_js
node_js:
  - "8"
  - "6"
env:
  # We set our own flag to tell our test code that it is running in a continuous
  # integration environment. (Travis sets CI and TRAVIS but the former is too
  # liable to collision (some other tool may use CI) and the latter is too
  # specific (we could use something else than Travis).)
  - CONTINUOUS_INTEGRATION=1
before_install:
  # On Node v4 the version of npm is too old.
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - sudo add-apt-repository "deb http://tei.oucs.ox.ac.uk/teideb/binary ./"
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-key FEA4973F86A9A497
  - sudo apt-get update -qq
  - sudo apt-get install -y xsltproc jing saxon
script: gulp test
branches:
  except:
    # A change to master has an identical corresponding change on develop
    # so if develop is tested (and it is), then it is redundant to *also*
    # test master. Let's be nice and minimize our use of Travis' resources.
    - master
