language: node_js
node_js:
  - "5.6"
  - "4.3"
  - "0.12"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xsltproc jing
script: gulp test
branches:
  except:
    # A change to master has an identical corresponding change on develop
    # so if develop is tested (and it is), then it is redundant to *also*
    # test master. Let's be nice and minimize our use of Travis' resources.
    - master
