language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_install:
  # On Node v4 the version of npm is too old.
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y xsltproc jing
script: gulp test
branches:
  except:
    # A change to master has an identical corresponding change on develop
    # so if develop is tested (and it is), then it is redundant to *also*
    # test master. Let's be nice and minimize our use of Travis' resources.
    - master
